################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
S_SRCS += \
../CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/SVC_Table.s 

C_SRCS += \
../CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/HAL_CM0.c \
../CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/HAL_CM3.c \
../CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/HAL_CM4.c 

S_DEPS += \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/SVC_Table.d 

C_DEPS += \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/HAL_CM0.d \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/HAL_CM3.d \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/HAL_CM4.d 

OBJS += \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/HAL_CM0.obj \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/HAL_CM3.obj \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/HAL_CM4.obj \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/SVC_Table.obj 

OBJS__QUOTED += \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\ARM\HAL_CM0.obj" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\ARM\HAL_CM3.obj" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\ARM\HAL_CM4.obj" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\ARM\SVC_Table.obj" 

C_DEPS__QUOTED += \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\ARM\HAL_CM0.d" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\ARM\HAL_CM3.d" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\ARM\HAL_CM4.d" 

S_DEPS__QUOTED += \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\ARM\SVC_Table.d" 

C_SRCS__QUOTED += \
"../CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/HAL_CM0.c" \
"../CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/HAL_CM3.c" \
"../CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/HAL_CM4.c" 

S_SRCS__QUOTED += \
"../CMSIS_5/CMSIS/RTOS/RTX/SRC/ARM/SVC_Table.s" 


