################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
S_SRCS += \
../CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/HAL_CM0.s \
../CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/HAL_CM3.s \
../CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/HAL_CM4.s \
../CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/SVC_Table.s 

S_DEPS += \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/HAL_CM0.d \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/HAL_CM3.d \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/HAL_CM4.d \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/SVC_Table.d 

OBJS += \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/HAL_CM0.obj \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/HAL_CM3.obj \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/HAL_CM4.obj \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/SVC_Table.obj 

OBJS__QUOTED += \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\IAR\HAL_CM0.obj" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\IAR\HAL_CM3.obj" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\IAR\HAL_CM4.obj" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\IAR\SVC_Table.obj" 

S_DEPS__QUOTED += \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\IAR\HAL_CM0.d" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\IAR\HAL_CM3.d" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\IAR\HAL_CM4.d" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\IAR\SVC_Table.d" 

S_SRCS__QUOTED += \
"../CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/HAL_CM0.s" \
"../CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/HAL_CM3.s" \
"../CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/HAL_CM4.s" \
"../CMSIS_5/CMSIS/RTOS/RTX/SRC/IAR/SVC_Table.s" 


