################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
S_UPPER_SRCS += \
../CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/HAL_CM0.S \
../CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/HAL_CM3.S \
../CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/HAL_CM4.S \
../CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/SVC_Table.S 

OBJS += \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/HAL_CM0.obj \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/HAL_CM3.obj \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/HAL_CM4.obj \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/SVC_Table.obj 

S_UPPER_DEPS += \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/HAL_CM0.d \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/HAL_CM3.d \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/HAL_CM4.d \
./CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/SVC_Table.d 

S_UPPER_DEPS__QUOTED += \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\GCC\HAL_CM0.d" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\GCC\HAL_CM3.d" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\GCC\HAL_CM4.d" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\GCC\SVC_Table.d" 

OBJS__QUOTED += \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\GCC\HAL_CM0.obj" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\GCC\HAL_CM3.obj" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\GCC\HAL_CM4.obj" \
"CMSIS_5\CMSIS\RTOS\RTX\SRC\GCC\SVC_Table.obj" 

S_UPPER_SRCS__QUOTED += \
"../CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/HAL_CM0.S" \
"../CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/HAL_CM3.S" \
"../CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/HAL_CM4.S" \
"../CMSIS_5/CMSIS/RTOS/RTX/SRC/GCC/SVC_Table.S" 


